title: 统计之都海外沙龙
email: contact@cos.name
description: 
keywords: "R语言, 数据科学，数据分析, 数据挖掘, 机器学习, 商业智能, 大数据"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

qiniubaseurl: "http://saloncdn.xueqingtv.com"  # qiniu CDN speedup

# Build settings
markdown: kramdown
permalink: /video/:year-:month-:day/:title/

gems: [jekyll-paginate]

paginate: 10
paginate_path: "history/page:num"

ad:
    image: 'http://saloncdn.xueqingtv.com/images/logo-chinar-ad.png'
    url: 'http://china-r.org/'
    area: 
        width: 360
        height: 150